# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Tempo.app — the whole app: server, shell and web UI in one bundle.

This used to build only a `tempo-server` sidecar that a Tauri/Rust binary spawned. With the
shell rewritten in Python there is one process and one build step, and `BUNDLE` emits the .app
itself — which also retires the symlink/framework flattening that Tauri's resource bundler
forced the build script to work around.

Wrinkles handled here:
  - uvicorn loads its protocol/lifespan implementations by string name at runtime, so static
    analysis misses them entirely -> collect_all.
  - certifi's CA bundle must ship or every TLS call fails: that is both Together AI and the
    whole Google Calendar integration.
  - pyobjc reaches AppKit/WebKit through lazy framework loading; the pyobjc hooks cover the
    bindings, but the framework packages we import are named explicitly to be safe.
  - the web UI and the splash are read from disk at runtime -> shipped as data and resolved
    through paths.resource_dir().
  - the Google OAuth client is baked in at build time; a packaged app has no repo-root .env.
  - the updater imports cryptography lazily, inside the function that verifies a download, so
    its Ed25519 module is named explicitly rather than trusted to static analysis.

Paths derive from SPECPATH, never hardcoded. Apple Silicon only, per project scope:
target_arch is left unset so PyInstaller builds for the host.
"""

import os
import sys

from PyInstaller.utils.hooks import collect_all, collect_submodules

PACKAGING = SPECPATH
ROOT = os.path.dirname(PACKAGING)

sys.path.insert(0, ROOT)
from desktop import __version__ as VERSION  # noqa: E402  (single source of truth for the version)

hiddenimports = []
datas = []
binaries = []

# The app itself. pathex below lets PyInstaller resolve these imports from app_entry.
# backend.tests is excluded below; filtering it here too keeps PyInstaller from logging every
# test module as a "Hidden import not found" error.
hiddenimports += collect_submodules("backend", filter=lambda name: not name.startswith("backend.tests"))
hiddenimports += collect_submodules("desktop")

# uvicorn: dynamic imports (see module docstring). certifi: the CA bundle. anyio: the async
# backend FastAPI runs on, also loaded by name.
for pkg in ("uvicorn", "certifi", "anyio"):
    d, b, h = collect_all(pkg)
    datas += d
    binaries += b
    hiddenimports += h

# uvicorn[standard] extras — present in this venv, but import-guarded so a slimmer
# environment still builds.
for pkg in ("uvloop", "httptools", "websockets", "watchfiles"):
    try:
        hiddenimports += collect_submodules(pkg)
    except Exception:
        pass

# The updater's signature check (backend/app/updater.py). pyinstaller-hooks-contrib's
# cryptography hook ships the compiled `_rust` extension and its OpenSSL; the modules actually
# used are imported inside verify_archive(), so they are listed here as well.
hiddenimports += [
    "cryptography.exceptions",
    "cryptography.hazmat.primitives.asymmetric.ed25519",
    "cryptography.hazmat.bindings._rust",
]

# The Cocoa shell. PyObjCTools.AppHelper is imported inside a function, and the framework
# packages are resolved lazily by pyobjc itself, so none of these are found by static analysis.
hiddenimports += ["objc", "Foundation", "AppKit", "WebKit", "PyObjCTools.AppHelper"]

# Outreach. claude_code.py imports the Claude Agent SDK inside generate(), and outreach.py reads
# PDF resumes with PDFKit (Quartz) inside _pdf_text(), so neither is seen by static analysis.
hiddenimports += collect_submodules("claude_agent_sdk")
hiddenimports += ["Quartz"]

# Read from disk at runtime rather than embedded in the Python.
datas += [
    (os.path.join(ROOT, "web"), "web"),
    (os.path.join(ROOT, "desktop", "splash"), os.path.join("desktop", "splash")),
]

# The OAuth client baked in at build time. Generated by the build script from
# GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET; absent in a plain local build, in which case the app
# falls back to reading them from the environment (config.google_client_id()).
_oauth_client = os.path.join(PACKAGING, "oauth_client.json")
if os.path.exists(_oauth_client):
    datas += [(_oauth_client, ".")]
else:
    print("WARNING: packaging/oauth_client.json missing — the bundled app will have no Google "
          "OAuth client and 'Connect Google Calendar' will be disabled.")

a = Analysis(
    [os.path.join(PACKAGING, "app_entry.py")],
    pathex=[ROOT],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "PIL", "PyQt5", "PySide6", "backend.tests"],
    noarchive=False,
)
# The SDK wheel carries its own Claude Code CLI (claude_agent_sdk/_bundled/claude, ~225 MB).
# Tempo always runs the user's installed Claude Code (claude_code.find_cli() → cli_path), so a
# bundled copy would be dead weight: it would make the .dmg and every update download several
# times larger. Dropped here in case any hook collects it.
def _not_bundled_cli(entry):
    return "claude_agent_sdk/_bundled" not in entry[0].replace(os.sep, "/")


a.datas = [e for e in a.datas if _not_bundled_cli(e)]
a.binaries = [e for e in a.binaries if _not_bundled_cli(e)]

pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Tempo",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    # Windowed: no terminal behind the app. This leaves sys.stdout/sys.stderr as None, which
    # would break uvicorn's logging — desktop/main.py repoints them at ~/.tempo/logs first.
    console=False,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="Tempo",
)
app = BUNDLE(
    coll,
    name="Tempo.app",
    icon=os.path.join(ROOT, "desktop", "icons", "icon.icns"),
    bundle_identifier="com.tempo.desktop",
    version=VERSION,
    info_plist={
        "CFBundleName": "Tempo",
        "CFBundleDisplayName": "Tempo",
        "CFBundleShortVersionString": VERSION,
        "CFBundleVersion": VERSION,
        "LSMinimumSystemVersion": "12.0",
        "NSHighResolutionCapable": True,
        "LSApplicationCategoryType": "public.app-category.productivity",
        # The window loads http://localhost:<port>. App Transport Security blocks plaintext
        # HTTP by default, and this is the narrow exemption for local addresses — without it
        # the webview shows a blank page instead of the UI.
        "NSAppTransportSecurity": {"NSAllowsLocalNetworking": True},
    },
)
