# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the bundled `tempo-server` (desktop sidecar).

One-DIR bundle (exe + `_internal/` support folder), shipped via Tauri's `resources` slot.
Deliberately not onefile: onefile re-extracts its whole archive to a temp dir on every launch,
which in OpenWorker cost 6-7 seconds of splash screen on each start.

Wrinkles handled here:
  - uvicorn loads its protocol/lifespan implementations by string name at runtime, so static
    analysis misses them entirely -> collect_all.
  - certifi's CA bundle must ship or every TLS call fails: that is both Together AI and the
    whole Google Calendar integration.
  - the web UI is read from disk at runtime (backend/app/main.py WEB_DIR) -> ship `web/` as
    data and resolve it through paths.resource_dir().
  - the Google OAuth client is baked in at build time; a packaged app has no repo-root .env.

Paths derive from SPECPATH, never hardcoded. Apple Silicon only, per project scope:
target_arch is left unset so PyInstaller builds for the host.
"""

import os

from PyInstaller.utils.hooks import collect_all, collect_submodules

PACKAGING = SPECPATH
ROOT = os.path.dirname(PACKAGING)

hiddenimports = []
datas = []
binaries = []

# The app itself. pathex below lets PyInstaller resolve the `backend.*` imports in server_entry.
hiddenimports += collect_submodules("backend")

# uvicorn: dynamic imports (see module docstring). certifi: the CA bundle. anyio: the async
# backend FastAPI runs on, also loaded by name.
for pkg in ("uvicorn", "certifi", "anyio"):
    d, b, h = collect_all(pkg)
    datas += d
    binaries += b
    hiddenimports += h

# uvicorn[standard] extras — present in this venv, but import-guarded so a slimmer
# environment still builds.
for pkg in ("uvloop", "httptools", "websockets", "watchfiles"):
    try:
        hiddenimports += collect_submodules(pkg)
    except Exception:
        pass

# The web UI, loaded from disk at runtime rather than embedded in the Python.
datas += [(os.path.join(ROOT, "web"), "web")]

# The OAuth client baked in at build time. Generated by the build script from
# GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET; absent in a plain local build, in which case the app
# falls back to reading them from the environment (config.google_client_id()).
_oauth_client = os.path.join(PACKAGING, "oauth_client.json")
if os.path.exists(_oauth_client):
    datas += [(_oauth_client, ".")]
else:
    print("WARNING: packaging/oauth_client.json missing — the bundled app will have no Google "
          "OAuth client and 'Connect Google Calendar' will be disabled.")

a = Analysis(
    [os.path.join(PACKAGING, "server_entry.py")],
    pathex=[ROOT],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "PIL", "PyQt5", "PySide6", "backend.tests"],
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="tempo-server",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    # Console build on purpose: a windowed (console=False) build leaves sys.stdout/stderr as
    # None, which breaks uvicorn's startup logging and hangs the server. The Tauri shell will
    # redirect this to a log file rather than showing a terminal.
    console=True,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="tempo-server",
)
